set_property PACKAGE_PIN R3 [get_ports clk] 
set_property IOSTANDARD LVCMOS33 [get_ports clk] 
set_property PACKAGE_PIN P4 [get_ports in] 
set_property IOSTANDARD LVCMOS33 [get_ports in] 
set_property PACKAGE_PIN T8 [get_ports out] 
set_property IOSTANDARD LVCMOS33 [get_ports out] 