# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/orithu/桌面/FORTH/c_1/c_A.cache/wt [current_project]
set_property parent.project_path /home/orithu/桌面/FORTH/c_1/c_A.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/orithu/桌面/FORTH/c_1/c_A.srcs/sources_1/new/c_A.v
read_xdc /home/orithu/桌面/FORTH/c_1/c_A.srcs/constrs_1/new/c_A_con.xdc
set_property used_in_implementation false [get_files /home/orithu/桌面/FORTH/c_1/c_A.srcs/constrs_1/new/c_A_con.xdc]

synth_design -top c_A -part xc7a100tcsg324-1
write_checkpoint -noxdef c_A.dcp
catch { report_utilization -file c_A_utilization_synth.rpt -pb c_A_utilization_synth.pb }
